version = 0.1

[default.deploy.parameters]
stack_name = "todo-backend"
resolve_s3 = true
s3_prefix = "todo-backend"
region = "eu-west-1"
profile = "dev_ibrahim"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
disable_rollback = true
